### PR TITLE
New release

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by Erick555** [comment]
@hughsie you won't need those gudev patches if you move to gnome 3.34 and new [gudev submodule](https://github.com/flathub/shared-modules/blob/master/gudev/gudev.json)

**Comment by hughsie** [comment]
Thanks @Erick555 -- I did that on master, thanks!

**Comment by superm1** [comment]
Does that mean we don't need to carry the old gudev version patch in fwupd either and can rev the min version requirements?

IIRC flatpak was the main reason

**Comment by hughsie** [comment]
https://github.com/fwupd/fwupd/pull/1528

**Pull request merged**
